version: "3"
services:
    nginx:
        restart: always
        image: nginx
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./default.conf:/etc/nginx/conf.d/default.conf
    php:
        restart: always
        image: php:fpm
        volumes:
            - ./code:/code
            - ./php.ini:/usr/local/etc/php/php.ini
    mysql:
        image: mariadb
        container_name: mysql
        command: --transaction-isolation=READ-COMMITTED --log-bin=ROW
        restart: unless-stopped
        volumes: 
            - ./database:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
            MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
            MYSQL_DATABASE: testdb
            MYSQL_USER: testuser
            MYSQL_INITDB_SKIP_TZINFO: 1
        secrets:
          - mysql_root_password
          - mysql_user_password
        ports:
            - "3306:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: your_root_password
        ports:
            - "8081:80"
        restart: always
        volumes:
            - ./php.ini:/usr/local/etc/php/php.ini
secrets:
        mysql_root_password:
          file: ./secrets/mysql_root_password
        mysql_user_password:
          file: ./secrets/mysql_user_password
